name: flavored_patrol
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  patrol: ^3.15.2

flutter:
  uses-material-design: true

patrol:
  app_name: '[Q] Patrol'
  flavor: qa
  android:
    package_name: com.example.flavored_patrol.qa
  ios:
    bundle_id: com.example.flavoredPatrol.qa